# Generated by Django 3.2 on 2021-04-21 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='alias',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='trail',
            old_name='trail_name',
            new_name='hike_name',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='hike',
        ),
        migrations.DeleteModel(
            name='Hike',
        ),
    ]
