# Generated by Django 3.2 on 2021-04-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0003_trail_hike_zip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='hike_zip',
        ),
        migrations.AddField(
            model_name='trail',
            name='hike_city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
