# Generated by Django 3.2 on 2021-04-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0005_trail_hike_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='hike_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
