# Generated by Django 3.2 on 2021-04-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0009_trail_hike_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trail',
            name='hike_description',
            field=models.TextField(),
        ),
    ]
