# Generated by Django 3.2 on 2021-04-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0010_auto_20210425_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='hike_milage',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
